sudo: false
language: node_js
node_js:
- "node"
- "4.2"
cache:
  directories:
  - node_modules
env:
  global:
  - secure: ejbwPFoEiW/R6JPAP1EFpweflpq3tQpgn6g0u+d6mAdH0Wh2x7zBIB6X3mH/T2q4ebjRXvszbgaCW78uZUtjFrK5MDqZUe2MPP9mJfwfKJTPffUNVNLgvdM63ZkCeJ1e7/qICZz8SQIdGNE7UeLcs6iWRO0peB9IpmRRFT2T2/Pe2LT9ktq02z46mLP/e9ogSMd7fw7TgbZdN+KsvDzhI/wO1PK7ugS8A3Ke3VT3nR4pOiKqjE8E0mxHSP7dEadTMsQ7cEd9vXRkV3Z3Ncq5mKjn6yRTPFKoXEwW1Lal9HCE3MkVA1xJY3pxKWpvP+XvH9rFwVrtEYTLZWX7f5MFsygcSJSbdBVv4IkV63VwcCX3Ne74L9e6ekhpGKNKh9mArIA6ZruWl5h3+VbXqKzemMoG5FLIzzQCNes9v0FE3ZNbvGl1Aik9plz7ygPZK04n2leoy5pYoFlzHDv4jrMxc9gvqTr+TES3ytr8L2D/AAlQBRT2bIZRDnMMwsWcmSfLzE9nYwme/bbDqLgR+In8RyX/Zqob3iYO9CiTgi+tPLBpGUzGeAaAh4iyGPokeXSxh3/6a36W+2dntxufAwWZCFupAp9N64eIL21gAsw0z4DQowRaPFSXRkfRLoIgbf0+N3lYos1uz2MvaXVhxYYqeUM9HZx7wAmLzxAB18L26Ec=
notifications:
  slack:
    secure: U8ll5RkW+ehC64PgGG6jsbrKIZC8adSMzCr1wC6TP6q6goBNQ/RbqLtR+hW+TMYsrLpIi7/T/93WojQOevqE46arNiVvZI+O1mS/Bm1osREfdcDxMjS6f7qZL+6RGz61PeepFLfgUvR5IMW2yx3oh1fSv/Vel4Ur0i4Mc20LB5vgeao79+uVw+HAsqTLsfK2dvApJgS7fGRjYc5amx2pMG9klz8vCJl+DQLAoPRctNfP1co6FVrr3ZXL1Y44aGvh05US5OhSk+8CtRkUKILmB1XwjQWYS/FlQwtZ1RU72caPdeWVIItqcTgvFxiQ2JyORl9SmD7/nfVb8FjL7+PymXQqdaQWq+3Gu4BqTtogaFABu+suvdsga54sIKm6nbqyLJ6KOXrGyBQ6DfClI8ECcKB/2AiW72OGSNot7DrrQz5DCpa+9eqI7cZzI3o/RLh1j4w6+30OkY54qceqWIYxOqxFWQEJ0/b74X6jTJ16TIM5eY5tg8EM8RyrtOZ+Z1XiJJMWLboAeeGSVjOWxZjoIKXNdOGn3IRxX7ZjDeYS+dTSHmjHuykSch0KNrVVrd7zIlEQ8nVkCTQA7RY62dreuwhOxfWqPrzyrNrqW733jaIhnsy5NbG6ssj9HPybyic3mzCdbdfOdKTpS7HiuBMRVS3+g27uF3eo4AQn7PRmKSg=
