sudo: false
language: node_js
node_js:
- node
- '4.2'
cache:
  directories:
  - node_modules
notifications:
  slack:
    on_success: change
    rooms:
      secure: G/iXUG2tP2kJAbOEh/hFqzx7hHfQLQtepQi9viIxIjAuBl/KgmxeoJXsktWWXqDZsV3YVq4JrCjsMDyqteM46O/flaktM0vAV012/OkKw9WTl7Et1k86ZyrEYrwj5FnP0602WMU6scDLYCPTad6jRL4MjfxMh5bXZws27hpGgiHZcHnoTbfFWCHkfz5Zwl/g93TNRczMPd8MtnZWY+GZpCCKEYzk67gZPCn3nMssKLplRDYzPLobvAE6jduKUuxV3Yg/FCWmgrxYOpqrQoz3F7zN8ZzKyt4+R4LVl2plpwImOXNlHm4tN/819iJ31gjzVSC2quYCHDAcfO6QmlCC8efbGL84JJU2BFoNw3JfK+vNPA/LkV8trXKfxoBoVFhGfpLWmGaNLUiKD8Cb38bFanb8ekbGqw+qFaKn2I9NxUInkHuT5fobbWpqvUreNnralrjlEjKdAbiCeStcxYivbREXc+AasWREICsgu4roUaXz1VEn4EY6uOb1vFVeyRh5gxKrUBulVFjt1SeOc9/UGPm3HIpyvXDP9yk414eLoS5pqlQTqNmZo510C4luOWq0kSvzGfjvLpyPRP7kEbGSJ2RMDO+rjsbcDI14ZFvaMWIo/cjCOnCf6J/UnZls3mB56tPokQllkzRqCbRbg0xWsgM5MrQeKoGqQA9/jrVIhgk=
